% *  This code was used in the following articles:
% *  [1] Learning 3-D Scene Structure from a Single Still Image, 
% *      Ashutosh Saxena, Min Sun, Andrew Y. Ng, 
% *      In ICCV workshop on 3D Representation for Recognition (3dRR-07), 2007.
% *      (best paper)
% *  [2] 3-D Reconstruction from Sparse Views using Monocular Vision, 
% *      Ashutosh Saxena, Min Sun, Andrew Y. Ng, 
% *      In ICCV workshop on Virtual Representations and Modeling 
% *      of Large-scale environments (VRML), 2007. 
% *  [3] 3-D Depth Reconstruction from a Single Still Image, 
% *      Ashutosh Saxena, Sung H. Chung, Andrew Y. Ng. 
% *      International Journal of Computer Vision (IJCV), Aug 2007. 
% *  [6] Learning Depth from Single Monocular Images, 
% *      Ashutosh Saxena, Sung H. Chung, Andrew Y. Ng. 
% *      In Neural Information Processing Systems (NIPS) 18, 2005.
% *
% *  These articles are available at:
% *  http://make3d.stanford.edu/publications
% * 
% *  We request that you cite the papers [1], [3] and [6] in any of
% *  your reports that uses this code. 
% *  Further, if you use the code in image3dstiching/ (multiple image version),
% *  then please cite [2].
% *  
% *  If you use the code in third_party/, then PLEASE CITE and follow the
% *  LICENSE OF THE CORRESPONDING THIRD PARTY CODE.
% *
% *  Finally, this code is for non-commercial use only.  For further 
% *  information and to obtain a copy of the license, see 
% *
% *  http://make3d.stanford.edu/publications/code
% *
% *  Also, the software distributed under the License is distributed on an 
% * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either 
% *  express or implied.   See the License for the specific language governing 
% *  permissions and limitations under the License.
% *
% */
function []=gen_fsup_new();
% This function generate the feature of the superpixel
% which will be shared by subsuperpixels

%%%
% For each image in filename, load
% scratch/data/MedSeg.MediResImgIndexSuperpixelSepi.mat
% generated by gen_Sup_new and call f_sup
% save the results for all images in
% scratch/data/FeatureSuperpixel.mat
%%%

% define general data folder and scratch data folder
global GeneralDataFolder ScratchDataFolder LocalFolder ClusterExecutionDirectory...
    ImgFolder VertYNuPatch HoriXNuPatch a_default b_default Ox_default Oy_default...
    Horizon_default filename;

% prepare data step
tic;
NuPics = size(filename,2); % number of pics
for i=1:NuPics
    i
    % load data
    load([ScratchDataFolder '/data/MedSeg/MediResImgIndexSuperpixelSep' num2str(i) '.mat']);
    % calculate all the features of superpixel
    % don't need to resize all the superpixel images to the same size since
    % all the feature calculated is be normalized to the size the the image
    [FeatureSuperpixel{i}]= f_sup(MediResImgIndexSuperpixelSep); % (hard work 5min) call f_sup to calculate the feature of superpixel
end
save([ScratchDataFolder '/data/FeatureSuperpixel.mat'],'FeatureSuperpixel'); % 
toc;
disp('feature of superpixel ready');
    
