fileID = fopen('data.txt','w');
fprintf(fileID,['%f %f %f %f %f %f ',... 
                '%f %f %f %f %f %f ',... 
                '%f %f %f %f %f %f ',... 
                '%f %f %f \n'],...
                [r1;t1;r2;t2;eyes;neck;waist]);
fclose(fileID);