dbclear all;
clc;

% compile matlab wrappers
disp('Building wrappers ...');
mex('FeaturesMex.cpp',...         % code to compile
    '-I../../cpp/icub/src',...  % add headers
    'CXXFLAGS=-msse3 -fPIC');
    %
    %'../src/viso.cpp',...
    %'../src/matcher.cpp',...
    %'../src/filter.cpp',...
    %'../src/triangle.cpp',...
    %'../src/matrix.cpp',...
disp('...done!');